version: '3.1'

services:
  database:
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: meli
      MYSQL_ROOT_PASSWORD: root

  cache:
    image: redis:6.2-alpine
    restart: always

  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "80:80"
    restart: always
    depends_on:
      - database
