version: '3.1'

services:
  database:
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: meli
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  cache:
    image: redis:6.2-alpine
    restart: always
    networks:
      - app-network

  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "80:80"
    restart: always
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
